Chorar por uma pessoa que esta morta nao e tao triste quanto chorar por uma uma pessoa que ainda vive mas que a perdemos para sempre.
Nao devemos nos questionar porque algumas coisas nos acontecem e sim o que podemos fazer com o tempo que nos e dado.
Nao existe triunfo sem perda, nao ha vitoria sem sofrimento, nao ha liberdade sem sacrificio.
Aquele que quebra uma coisa para descobrir o que ela e deixou o caminho da sabedoria.
Nada como procurar quando se quer achar alguma coisa. Quando se procura geralmente se encontra alguma coisa, sem duvida, mas nem sempre o que estavamos procurando.
Porque um homem que foge do seu medo pode descobrir que, afinal, apenas enveredou por um atalho para ir ao seu encontro.
Nao se adquire um bom vocabulario com a leitura de livros escritos conforme uma ideia do que seja o vocabulario da faixa etaria do leitor. Ele vem da leitura de livros acima da sua capacidade.
A Fantasia e escapista, e essa e a sua gloria. Se um soldado e aprisionado pelo inimigo, nao consideramos que e seu dever escapar?... Se valorizamos a liberdade da mente e da alma, se somos partidarios da liberdade, entao e nosso obvio dever escapar, e levar conosco tantas pessoas quanto conseguirmos!
Nunca gostei de Senhor dos Aneis e similares, nem dos livros de Tolkien. Tematicas fantasiosas sao alegorias sem conteudo. Sendo assim, confesso: prefiro enredo de escola de samba.
⁠e que da bem-aventuranca e da alegria na vida ha pouco a ser dito enquanto duram; assim como as obras belas e maravilhosas, enquanto perduram para que os olhos as contemplem, sao registros de si mesmas; e somente quando correm perigo ou sao destruidas e que se transformam em poesia.
Na verdade nem deveriamos estar aqui, mas estamos. Sao como nas grandes historias. As que tinham mesmo importância. Eram repletas de escuridao e perigo. E, as vezes, voce nao queria saber o fim... Porque como podiam ter um final feliz? Como podia o mundo voltar a ser o que era depois de tudo isso? Mas, no fim, e so uma coisa passageira, ate tudo passar. Um novo dia vira. E, quando o sol brilhar, brilhara ainda mais forte. Eram essas as historias que ficavam nas lembrancas, que significavam algo. Mesmo que voce fosse pequeno demais para entender o por que. Mas acho, que entendo, sim. Agora eu sei. As pessoas dessas historias tinham varias oportunidades de voltar atras mas nao voltavam. Elas seguiam em frente, porque tinham no que se agarrar.
